### ISSUE TITLE
"This workflow has no runs yet"

### ISSUE THREAD

**Issue by vitaly-zdanevich** [anc95/ChatGPT-CodeReview#153]
Created according to instruction - and looks like not running :(

The repo https://github.com/vitaly-zdanevich/geeknote

**Comment by vitaly-zdanevich** [comment]
[CI is running after adding `on: push`](https://github.com/vitaly-zdanevich/geeknote/commit/44a5f76baa2cad4bea205e5c689b8b87339c2912):

```
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, reopened, synchronize]

```

But not any review yet.
