### ISSUE TITLE
Got "no change found" after pushed new changes to PR

### ISSUE THREAD

**Issue by timmy-liu-paypay** [anc95/ChatGPT-CodeReview#161]
As title, I am using Github Actions as below

```
name: Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    # if: ${{ contains(github.event.*.labels.*.name, 'gpt review') }} # Optional; to run only when a label is attached
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

```
