### ISSUE TITLE
Support review folder

### ISSUE THREAD

**Issue by npquynhdo** [anc95/ChatGPT-CodeReview#167]
Instead of ignoring multiple files/folder. Isn't better to support a review folder?
Something like :
```
steps:
  - uses: anc95/ChatGPT-CodeReview@main
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PATH: ./src
```

**Comment by anc95** [comment]
@npquynhdo just added `INCLUDE_PATTERNS` support
```
steps:
  - uses: anc95/ChatGPT-CodeReview@main
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INCLUDE_PATTERNS: src/
```
