### ISSUE TITLE
I want to stop comments under certain conditions.

### ISSUE THREAD

**Issue by yamamoto-ehhMH** [anc95/ChatGPT-CodeReview#178]
>Please review for the following issues:
Bugs
N+1 queries
Possibility of refactoring
Only comment if there is a clear issue. Otherwise, just respond with 'no comment.'

I'm writing a prompt like this, but I want to prevent "no comment" from being included as a comment.

Is it possible to set it so that if the phrase "no comment" is included, no comment is made at all?

If there are other ways to stop specific comments, please let me know.

**Comment by anc95** [comment]
@yamamoto-ehhMH it makes sense, I can do this by the end of this week. stay tuned

**Comment by yamamoto-ehhMH** [comment]
@anc95 

Thank you for your prompt response.
I’m very excited to hear that the implementation will be ready by this weekend. Looking forward to it!

**Comment by anc95** [comment]
@yamamoto-ehhMH hello, just supported this in the latest version
like the [comment](https://github.com/anc95/ChatGPT-CodeReview/pull/182#pullrequestreview-2688526197), if all reviews are good, will response with a `LTGM 👍` message

**Comment by yamamoto-ehhMH** [comment]
@anc95 

Thank you for your prompt response! I'm very happy.

However, I may not have explained myself clearly.
Would it be possible to disable bot comments altogether?

Below, I’m sharing my current configuration file.
The issue I'm facing is that ChatGPT responds even when there are no issues in the code.

I was considering the following approach as a possible solution:

Instructing ChatGPT to return "no comment" when there are no issues
Configuring the bot to check if the response contains "no comment" and, if so, prevent it from being posted as a GitHub comment

You are already doing an amazing job, and I feel sorry for making additional requests...


```yml
name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    if: ${{ (github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref != 'develop') || (github.event.pull_request.base.ref == 'develop' && github.event.pull_request.head.ref != 'main') }}
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: Japanese
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4-turbo-2024-04-09 # https://platform.openai.com/docs/models
          PROMPT: |
            以下の点で問題があるかどうかレビューしてください。
            - バグ
            - N+1
            - リファクタできるか

            明確な問題がある時だけコメントしてください。
            それ以外は絶対に何もコメントしないでください。

          top_p: 1 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-top_p
          temperature: 1 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-temperature
          max_tokens: 4096
          MAX_PATCH_LENGTH: 10000 # if the patch/diff length is large than MAX_PATCH_LENGTH, will be ignored and won't review. By default, with no MAX_PATCH_LENGTH set, there is also no limit for the patch/diff length.
          # IGNORE_PATTERNS: /node_modules/**/*,*.md # glob pattern or regex pattern to ignore files, separated by comma
          INCLUDE_PATTERNS: "*.html,*.js,*.css,*.scss,*.sass,*.rb,*.erb,*.rake" # glob pattern or regex pattern to include files, separated by comma
```
