### ISSUE TITLE
bug: do not work on new commit to pull_request

### ISSUE THREAD

**Issue by Certseeds** [anc95/ChatGPT-CodeReview#32]
refer to <https://github.com/Certseeds/openpgpage/pull/4>
use actions to trigger code-review
``` yaml
name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    if: github.repository == 'Certseeds/openpgpage'
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.CHATGPT_SESSION_TOKEN }}
```
1st commit trigger a review, get a meaningful response.
2nd force-push trigger a review, find a meaingful response too.
but the 3rd and 4th push can trigger actions but do not find response, is that corect?
ps: 
the 3rd action <https://github.com/Certseeds/openpgpage/actions/runs/4315833869>
the 4th action <https://github.com/Certseeds/openpgpage/actions/runs/4315849686>
