### ISSUE TITLE
Run only on labeled PRs

### ISSUE THREAD

**Issue by JohannesArtmeier** [anc95/ChatGPT-CodeReview#43]
Hey,

I love it! Awesome job. I'm trying to run it only when I set a particular label for the PR (to save tokens for small PRs).

```
name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, labeled]

jobs:
  test:
    if: github.event.label.name == 'GPT-CR'
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: English
```

I also get the action triggered, but for some reason, no feedback is posted on the PR.
Here is the action result:
![image](https://user-images.githubusercontent.com/47254538/225929906-d18c23fa-3831-40ee-89e2-189d422f8ad1.png)

Any idea why no feedback is provided?
