### ISSUE TITLE
The 429 too many request error

### ISSUE THREAD

**Issue by tmdrb278** [anc95/ChatGPT-CodeReview#46]
The 429 too many request error appears in the open api, is it a bug? Or should I use the paid version?
this is error code
```
Error: OpenAI error 429: {
        "error": {
            "message": "You exceeded your current quota, please check your plan and billing details.",
            "type": "insufficient_quota",
            "param": null,
            "code": null
        }
    }
        at /home/runner/work/_actions/anc95/ChatGPT-CodeReview/main/action/index.cjs:153249:29
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
{
```
this is my yml code
```
name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          MODEL: gpt-3.5-turbo
          top_p: 1
          temperature: 1
```
