### ISSUE TITLE
如何配置中文回答？

### ISSUE THREAD

**Issue by JeromeLin** [anc95/ChatGPT-CodeReview#55]
配置了 LANGUAGE: Chinese，依然是英文回答

``` yml
name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Chinese
```
