### ISSUE TITLE
OPENAI_API_KEY configuration error: Issues during GitHub Action execution

### ISSUE THREAD

**Issue by julian-jeong** [anc95/ChatGPT-CodeReview#67]
I have a problem with OPENAI_API_KEY not being recognized.

![Screenshot 2023-04-10 at 00 30 56](https://user-images.githubusercontent.com/75078324/230781933-859a9e3f-eba2-402c-a27a-11d324991a6a.png)

- **In the first attempt,** I set the OPENAI_API_KEY variable in the Variables tab. The GitHub Action runs, but OPENAI_API_KEY is empty, and the error message says it cannot be found.
![Screenshot 2023-04-10 at 00 31 39](https://user-images.githubusercontent.com/75078324/230782057-4bfc11aa-6cf0-4259-8870-aa60df752975.png)

- **In the second attempt,** I set up the YAML file like this and pushed it, but OPENAI_API_KEY is still empty.
- Despite setting up the OPENAI_API_KEY in Actions secrets and variables, you are still encountering an issue where the OPENAI_API_KEY value is not being recognized.

```
name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
```
![Screenshot 2023-04-10 at 00 50 09](https://user-images.githubusercontent.com/75078324/230782883-e0c4e0fe-7145-4fea-9df8-cc24b6fe61b0.png)

![Screenshot 2023-04-10 at 00 33 36](https://user-images.githubusercontent.com/75078324/230782076-908c3dc0-aefb-465a-abdb-62028197bca0.png)

Please tell me how to solve the problem.🥲
