### ISSUE TITLE
Github Actions version doesn't seem to have enough permission to comment by default? Suggestions?

### ISSUE THREAD

**Issue by PeterDaveHello** [anc95/ChatGPT-CodeReview#88]
I tried to switch from GitHub Apps version to GitHub Actions version, but it seems default GITHUB_TOKEN won't have enough permission to comment, not sure if using a PAT would be a good idea, anyone got the same issue and how do you deal with it? Thanks!

https://github.com/transmission-remote-gui/transgui/actions/runs/5038925037/jobs/9036731668?pr=1302

```yml
env:
    GITHUB_TOKEN: ***
    OPENAI_API_KEY: 
    MODEL: gpt-4
    top_p: 1
    temperature: 0.2
Error: Resource not accessible by integration
{
  name: 'event',
  id: '5038925037',
  err: {
    type: 'RequestError',
    message: 'Resource not accessible by integration',
    stack: 'HttpError: Resource not accessible by integration\n' +
      '    at /home/runner/work/_actions/anc95/ChatGPT-CodeReview/main/action/index.cjs:4070:21\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async Job.doExecute (/home/runner/work/_actions/anc95/ChatGPT-CodeReview/main/action/index.cjs:34389:18)',
    name: 'HttpError',
    status: 403,
    response: {
      url: 'https://api.github.com/repos/transmission-remote-gui/transgui/issues/1302/comments',
```
